INSERT INTO country VALUES ('Afghanistan');
INSERT INTO country VALUES ('Albania');
INSERT INTO country VALUES ('Algeria');
INSERT INTO country VALUES ('Andorra');
INSERT INTO country VALUES ('Angola');
INSERT INTO country VALUES ('Antigua and Barbuda');
INSERT INTO country VALUES ('Argentina');
INSERT INTO country VALUES ('Armenia');
INSERT INTO country VALUES ('Australia');
INSERT INTO country VALUES ('Austria');
INSERT INTO country VALUES ('Azerbaijan');
INSERT INTO country VALUES ('Bahamas');
INSERT INTO country VALUES ('Bahrain');
INSERT INTO country VALUES ('Bangladesh');
INSERT INTO country VALUES ('Barbados');
INSERT INTO country VALUES ('Belarus');
INSERT INTO country VALUES ('Belgium');
INSERT INTO country VALUES ('Belize');
INSERT INTO country VALUES ('Benin');
INSERT INTO country VALUES ('Bhutan');
INSERT INTO country VALUES ('Bolivia');
INSERT INTO country VALUES ('Bosnia and Herzegovina');
INSERT INTO country VALUES ('Botswana');
INSERT INTO country VALUES ('Brazil');
INSERT INTO country VALUES ('Brunei');
INSERT INTO country VALUES ('Bulgaria');
INSERT INTO country VALUES ('Burkina Faso');
INSERT INTO country VALUES ('Burundi');
INSERT INTO country VALUES ('Cambodia');
INSERT INTO country VALUES ('Cameroon');
INSERT INTO country VALUES ('Canada');
INSERT INTO country VALUES ('Cape Verde');
INSERT INTO country VALUES ('Central African Republic');
INSERT INTO country VALUES ('Chad');
INSERT INTO country VALUES ('Chile');
INSERT INTO country VALUES ('China');
INSERT INTO country VALUES ('Colombia');
INSERT INTO country VALUES ('Comoros');
INSERT INTO country VALUES ('Congo (Dem. Rep.)');
INSERT INTO country VALUES ('Congo (Rep.)');
INSERT INTO country VALUES ('Costa Rica');
INSERT INTO country VALUES ('Cote d''Ivoire');
INSERT INTO country VALUES ('Croatia');
INSERT INTO country VALUES ('Cuba');
INSERT INTO country VALUES ('Cyprus');
INSERT INTO country VALUES ('Czech Republic');
INSERT INTO country VALUES ('Denmark');
INSERT INTO country VALUES ('Djibouti');
INSERT INTO country VALUES ('Dominica');
INSERT INTO country VALUES ('Dominican Republic');
INSERT INTO country VALUES ('East Timor');
INSERT INTO country VALUES ('Ecuador');
INSERT INTO country VALUES ('Egypt');
INSERT INTO country VALUES ('El Salvador');
INSERT INTO country VALUES ('Equatorial Guinea');
INSERT INTO country VALUES ('Eritrea');
INSERT INTO country VALUES ('Estonia');
INSERT INTO country VALUES ('Eswatini');
INSERT INTO country VALUES ('Ethiopia');
INSERT INTO country VALUES ('Fiji');
INSERT INTO country VALUES ('Finland');
INSERT INTO country VALUES ('France');
INSERT INTO country VALUES ('Gabon');
INSERT INTO country VALUES ('Gambia');
INSERT INTO country VALUES ('Georgia');
INSERT INTO country VALUES ('Germany');
INSERT INTO country VALUES ('Ghana');
INSERT INTO country VALUES ('Greece');
INSERT INTO country VALUES ('Grenada');
INSERT INTO country VALUES ('Guatemala');
INSERT INTO country VALUES ('Guinea');
INSERT INTO country VALUES ('Guinea-Bissau');
INSERT INTO country VALUES ('Guyana');
INSERT INTO country VALUES ('Haiti');
INSERT INTO country VALUES ('Honduras');
INSERT INTO country VALUES ('Hungary');
INSERT INTO country VALUES ('Iceland');
INSERT INTO country VALUES ('India');
INSERT INTO country VALUES ('Indonesia');
INSERT INTO country VALUES ('Iran');
INSERT INTO country VALUES ('Iraq');
INSERT INTO country VALUES ('Ireland');
INSERT INTO country VALUES ('Israel');
INSERT INTO country VALUES ('Italy');
INSERT INTO country VALUES ('Jamaica');
INSERT INTO country VALUES ('Japan');
INSERT INTO country VALUES ('Jordan');
INSERT INTO country VALUES ('Kazakhstan');
INSERT INTO country VALUES ('Kenya');
INSERT INTO country VALUES ('Kiribati');
INSERT INTO country VALUES ('Kuwait');
INSERT INTO country VALUES ('Kyrgyzstan');
INSERT INTO country VALUES ('Laos');
INSERT INTO country VALUES ('Latvia');
INSERT INTO country VALUES ('Lebanon');
INSERT INTO country VALUES ('Lesotho');
INSERT INTO country VALUES ('Liberia');
INSERT INTO country VALUES ('Libya');
INSERT INTO country VALUES ('Liechtenstein');
INSERT INTO country VALUES ('Lithuania');
INSERT INTO country VALUES ('Luxembourg');
INSERT INTO country VALUES ('Madagascar');
INSERT INTO country VALUES ('Malawi');
INSERT INTO country VALUES ('Malaysia');
INSERT INTO country VALUES ('Maldives');
INSERT INTO country VALUES ('Mali');
INSERT INTO country VALUES ('Malta');
INSERT INTO country VALUES ('Marshall Islands');
INSERT INTO country VALUES ('Mauritania');
INSERT INTO country VALUES ('Mauritius');
INSERT INTO country VALUES ('Mexico');
INSERT INTO country VALUES ('Micronesia');
INSERT INTO country VALUES ('Moldova');
INSERT INTO country VALUES ('Monaco');
INSERT INTO country VALUES ('Mongolia');
INSERT INTO country VALUES ('Montenegro');
INSERT INTO country VALUES ('Morocco');
INSERT INTO country VALUES ('Mozambique');
INSERT INTO country VALUES ('Myanmar');
INSERT INTO country VALUES ('Namibia');
INSERT INTO country VALUES ('Nauru');
INSERT INTO country VALUES ('Nepal');
INSERT INTO country VALUES ('Netherlands');
INSERT INTO country VALUES ('New Zealand');
INSERT INTO country VALUES ('Nicaragua');
INSERT INTO country VALUES ('Niger');
INSERT INTO country VALUES ('Nigeria');
INSERT INTO country VALUES ('North Macedonia');
INSERT INTO country VALUES ('Norway');
INSERT INTO country VALUES ('Oman');
INSERT INTO country VALUES ('Pakistan');
INSERT INTO country VALUES ('Palau');
INSERT INTO country VALUES ('Panama');
INSERT INTO country VALUES ('Papua New Guinea');
INSERT INTO country VALUES ('Paraguay');
INSERT INTO country VALUES ('Peru');
INSERT INTO country VALUES ('Philippines');
INSERT INTO country VALUES ('Poland');
INSERT INTO country VALUES ('Portugal');
INSERT INTO country VALUES ('Qatar');
INSERT INTO country VALUES ('Romania');
INSERT INTO country VALUES ('Russia');
INSERT INTO country VALUES ('Rwanda');
INSERT INTO country VALUES ('St. Kitts and Nevis');
INSERT INTO country VALUES ('St. Lucia');
INSERT INTO country VALUES ('St. Vincent and the Grenadines');
INSERT INTO country VALUES ('Samoa');
INSERT INTO country VALUES ('San Marino');
INSERT INTO country VALUES ('Sao Tome and Principe');
INSERT INTO country VALUES ('Saudi Arabia');
INSERT INTO country VALUES ('Senegal');
INSERT INTO country VALUES ('Serbia');
INSERT INTO country VALUES ('Seychelles');
INSERT INTO country VALUES ('Sierra Leone');
INSERT INTO country VALUES ('Singapore');
INSERT INTO country VALUES ('Slovakia');
INSERT INTO country VALUES ('Slovenia');
INSERT INTO country VALUES ('Solomon Islands');
INSERT INTO country VALUES ('Somalia');
INSERT INTO country VALUES ('South Africa');
INSERT INTO country VALUES ('South Sudan');
INSERT INTO country VALUES ('Spain');
INSERT INTO country VALUES ('Sri Lanka');
INSERT INTO country VALUES ('Sudan');
INSERT INTO country VALUES ('Suriname');
INSERT INTO country VALUES ('Sweden');
INSERT INTO country VALUES ('Switzerland');
INSERT INTO country VALUES ('Syria');
INSERT INTO country VALUES ('Taiwan');
INSERT INTO country VALUES ('Tajikistan');
INSERT INTO country VALUES ('Tanzania');
INSERT INTO country VALUES ('Thailand');
INSERT INTO country VALUES ('Togo');
INSERT INTO country VALUES ('Tonga');
INSERT INTO country VALUES ('Trinidad and Tobago');
INSERT INTO country VALUES ('Tunisia');
INSERT INTO country VALUES ('Turkey');
INSERT INTO country VALUES ('Turkmenistan');
INSERT INTO country VALUES ('Tuvalu');
INSERT INTO country VALUES ('Uganda');
INSERT INTO country VALUES ('Ukraine');
INSERT INTO country VALUES ('United Arab Emirates');
INSERT INTO country VALUES ('United Kingdom');
INSERT INTO country VALUES ('United States of America');
INSERT INTO country VALUES ('Uruguay');
INSERT INTO country VALUES ('Uzbekistan');
INSERT INTO country VALUES ('Vanuatu');
INSERT INTO country VALUES ('Vatican City');
INSERT INTO country VALUES ('Venezuela');
INSERT INTO country VALUES ('Vietnam');
INSERT INTO country VALUES ('Yemen');
INSERT INTO country VALUES ('Zambia');
INSERT INTO country VALUES ('Zimbabwe');
INSERT INTO country VALUES ('Kosovo');